### ISSUE TITLE
RNN for images

### ISSUE THREAD

**Issue by RaviTej310** [kbullaughey/lstm-play#3]

**Comment by kbullaughey** [comment]
Are the images temporarily correlated in some way such that this is a sequence problem? Normally RNNs are most helpful when it's sequence data with correlation structure along the sequence that you're hoping the RNN will learn, and when the sequence lengths vary. In your situation, without knowing more about your particular problem it's hard to make concrete recommendations. In the deep-net world, 2k training examples may not be sufficient data. You may find you get better milage out of using a network trained for some other image classification problem, and use it as a feature extractor (e.g., [OverFeat](http://cilvr.nyu.edu/doku.php?id=software:overfeat:start)) and then use these features with some other statistical model or ML blackbox that tends to work well with less data.

As a side note, in general github issues are generally used for discussions of the source code, instead of general conversations. My email address and twitter handle ([@kbullaughey](https://twitter.com/kbullaughey)) are noted on the blog post. I'll close this issue for now.
